version: 0.0
Resources:
- TargetService:
Type: AWS::ECS::Service
Properties:
TaskDefinition: "aarn:aws:ecs:us-east-1:156962844638:task-definition/pms-890536-penstion-pro-rep-TD:1"
LoadBalancerInfo:
ContainerName: "pms-890536-penstion-pro-rep-CNT"
ContainerPort: 5000
PlatformVersion: "LATEST"
