version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws --version
    - $(aws ecr get-login --region us-east-1 --no-include-email)
    
  build:
    commands:
    - echo Build started on `date`
    - echo Building Java
    - cd ProcessPension-Microservice
    - mvn compile
    - mvn package -DskipTests
    - echo Building the docker image..
    - docker build -t pms-penstion-pro-rep .
    - docker tag pms-penstion-pro-rep:latest 156962844638.dkr.ecr.us-east-1.amazonaws.com/pms-penstion-pro-rep:latest
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing docker image
    - docker push 156962844638.dkr.ecr.us-east-1.amazonaws.com/pms-penstion-pro-rep:latest
    - echo Writting definition file
    - printf '[{"name":"PensionManagementPortal","imageUri":"%s"}]'  156962844638.dkr.ecr.us-east-1.amazonaws.com/pms-penstion-pro-rep:latest > imagedefinitions.json
artifacts:
  files:
  - ProcessPension-Microservice/imagedefinitions.json